### ISSUE TITLE
Scroll on Initialization

### ISSUE THREAD

**Issue by dancaron** [theomessin/vue-chat-scroll#15]
Hi, thanks for your work on this plugin.

I was wondering if it's possible to have the plugin scroll to bottom on initialization? Picture a chat window that already has many chats. Often times, you want to pick up at the most recent part of conversation. And having to scroll down, or wait for new message to scroll is not ideal. Does that make sense?

**Comment by theomessin** [comment]
Pretty sure I've already implemented that 😝 see #3. If I haven't though I'll do that too.

**Comment by dancaron** [comment]
So how would I implement this functionality? That thread (#3) only references a commit. I looked through the commit but could not find a setting that implement scroll on init.

**Comment by theomessin** [comment]
If I remember correctly, this line should do everything for you...
https://github.com/theomessin/vue-chat-scroll/blob/a08258dc917c04435e4165486a84834001d80718/src/directives/v-chat-scroll.js#L17

I'm guessing that it's not working anymore though. I'll see what I can do 😃

**Comment by dancaron** [comment]
No it doesn't seem to be working. Thanks for looking into it. Appreciate it!

**Comment by theomessin** [comment]
Long story short, I've been busy. Sat down to fix this issue but I couldn't replicate it. Plugin works fine and scrolls on page load: http://jsfiddle.net/yMv7y/3470/

Any chance you can show me some code?

**Comment by pmochine** [comment]
Yeah, I have got the same issue, unfortunately. I cannot recreate my modal, because I'm using vue-js-modal, but perhaps you get the idea with this jsfiddle: https://jsfiddle.net/d1oy67a2/

I try to explain what I'm doing. 
In my main.js I've  imported the file with:

```
import VueChatScroll from 'vue-chat-scroll'
Vue.use(VueChatScroll)
```

My chat is based on the vue-js-modal. When you get to the conversations, it is loaded like that:

```
<ol class="list-group pt-3" v-chat-scroll>
	<conversation-line 
		v-for="(line, index) in conversations" 
		:key="index"
		:message="line"
	></conversation-line>
</ol>
```

The conversation-line contains <li> elements.

But still no luck it just does not want to scroll down. Even if I write a new message. What I'm doing wrong? 

![blubb](https://user-images.githubusercontent.com/25006691/42126178-cdb4a49e-7c83-11e8-9d63-a7b8e92b4fb8.gif)

**Comment by pmochine** [comment]
And p.s. if i just write somewhere 

```
<div>
       <ul class="chatroom" v-chat-scroll style="height:200px; overflow: auto;">
        <li class="message" v-for="m in 50">
          <b v-text="m"></b>
        </li>    
      </ul>      
    </div>
```

then it works perfectly...

**Comment by theomessin** [comment]
@pmochine any chance you could add this in the docs yourself? Just fork, edit, and create pull request :wink:
