### ISSUE TITLE
Prevent scroll down when user has scrolled up

### ISSUE THREAD

**Issue by RMK147** [theomessin/vue-chat-scroll#2]
Hello,

I'm using this in a chat app to scroll to the bottom of a div when a new message is received. The problem is if the user has scrolled up within the div (to view older messages), then when they receive a new message it automatically scrolls to the bottom, which is annoying. Could an option be added for it to only scroll down, if the user hasn't scrolled up?

Thanks!

**Comment by theomessin** [comment]
I've got a general idea on how to do this. However, I will be doing a rewrite the entire code from the group-up first. I forked this repository because I too had to create a chat room using vue. Thus, eventually I will be renaming this repo to `vue-chat-scroll` and I will add a bunch of new features, including this one 😉

**Comment by theomessin** [comment]
4f177120188f97d50712a9ebef8a0a23deef49f8

**Comment by kennyki** [comment]
@theomessin is this already on your roadmap? Otherwise I have just created a pull request to support it (as I need it urgently). You may take a look at it.

Thanks

**Comment by theomessin** [comment]
#4 I was going to code this today 😝 Merged: 9813049ea9b92cabc8dd70ffe961f4077605f8f7

**Comment by kennyki** [comment]
Wow that was quick 👍 

Would you mind to bump the package version and register it on npm?

**Comment by theomessin** [comment]
Done
