### ISSUE TITLE
Forked project and add new feature: emit loading events when scroll to the top

### ISSUE THREAD

**Issue by sj82516** [theomessin/vue-chat-scroll#20]
Hi theomessin ,
Thanks for the useful vue directive project. I forked your project and modified a little bit to add new feature.  
When scroll to the top of element, directive would emit 'scroll-top' event.  
This would woks more like a chat box situation.  
Here is my [jsfiddle demo](https://jsfiddle.net/sj82516/780eg0ek/) 、[npm package](https://www.npmjs.com/package/vue-chat-scroll-top-scroll).
It's my first time to fork others project and republish by myself. 
If I do something wrong, please let me and I would fix ASPA.  
Thanks again.

**Comment by theomessin** [comment]
Hello, sorry for the delay (had too many GitHub notifications and this got buried). I really appreciate your work on this package. Just an FYI: when a fork only contains some minor extra features it is usually best to simply issue a pull request back to the original repo instead of republishing. This way your code gets more exposure and gets to help more people 😃 Either way, great work on the emit mod!

**Comment by sj82516** [comment]
Thanks for your reply. 
I would create issue first next time.
Really appreciate! 👍

**Comment by vesper8** [comment]
so.. did this get merged in or not ?

**Comment by theomessin** [comment]
There was no pull request to merge 🤷‍♂️ If I ever get one, I'll merge it. If not, I might code this extra feature myself (although I don't really see the use - I'll need some upvotes on this comment to do that).
